import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "./globals.css";
import { StoreProvider } from "../../store/StoreProvider";
import { CartSidebar } from "../../components/Cart/CartSideBar";
import GlobalChatInitializer from "../../components/chat/GlobalChatInitializer";
import FloatingChatWidget from "../../components/chat/FloatingChatWidget";

// Font chính (Inter)
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

// Font tiêu đề (Oswald)
const oswald = Oswald({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "AMEKO",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`custom-scrollbar ${inter.variable} ${oswald.variable} antialiased font-sans`}
      >
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            <GlobalChatInitializer />
            {children}
            <CartSidebar />
            <FloatingChatWidget />
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
